# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Init <- function(MaxT, NSites, MaxX, w, xc, B0, b0, b1, b2, pred_a1, pred_a2, c, speed, WindAssist, WindProb, ZStdNorm, PStdNorm, nTR_x, nTR_y, decError, dist, x_gain, y_gain, p_gain, expend) {
    invisible(.Call(`_sdpMig_Init`, MaxT, NSites, MaxX, w, xc, B0, b0, b1, b2, pred_a1, pred_a2, c, speed, WindAssist, WindProb, ZStdNorm, PStdNorm, nTR_x, nTR_y, decError, dist, x_gain, y_gain, p_gain, expend))
}

BackwardIteration <- function() {
    .Call(`_sdpMig_BackwardIteration`)
}

InitSim <- function(MaxT, NSites, MaxX, w, xc, B0, b0, b1, b2, pred_a1, pred_a2, c, speed, WindAssist, WindProb, ZStdNorm, PStdNorm, nTR_x, nTR_y, decError, dist, x_gain, y_gain, p_gain, expend, FMatrix, DMatrix1, DMatrix2, PMatrix1, PMatrix2) {
    invisible(.Call(`_sdpMig_InitSim`, MaxT, NSites, MaxX, w, xc, B0, b0, b1, b2, pred_a1, pred_a2, c, speed, WindAssist, WindProb, ZStdNorm, PStdNorm, nTR_x, nTR_y, decError, dist, x_gain, y_gain, p_gain, expend, FMatrix, DMatrix1, DMatrix2, PMatrix1, PMatrix2))
}

simForaging <- function(f_intensity, time, site, x) {
    .Call(`_sdpMig_simForaging`, f_intensity, time, site, x)
}

simFlying <- function(decision, time, site, x) {
    .Call(`_sdpMig_simFlying`, decision, time, site, x)
}

forwardSim <- function(Ind, start_time, start_site, start_x) {
    .Call(`_sdpMig_forwardSim`, Ind, start_time, start_site, start_x)
}

